apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka
spec:
  selector:
    matchLabels:
      app: eureka
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
      - name: eureka
        image: kelog/eureka-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8761
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: eureka
        - name: JAVA_OPTS
          value: '-Xmx100m'
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
spec:
  selector:
    app: eureka
  ports:
  - port: 8761
    targetPort: 8761
    
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-outside
spec:
  type: NodePort
  selector:
    app: eureka
  ports:
  - port: 8761
    targetPort: 8761
    nodePort: 31001

#########################################################

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      app: worker
  replicas: 1
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
      - name: worker
        image: kelog/eureka-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: worker
        - name: JAVA_OPTS
          value: '-Xmx100m'
        - name: EUREKA_URL
          value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: worker
spec:
  selector:
    app: worker
  ports:
  - port: 8081


#########################################################

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: kelog/eureka-demo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: gateway
        - name: JAVA_OPTS
          value: '-Xmx100m'
        - name: EUREKA_URL
          value: http://eureka:8761/eureka/
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  selector:
    app: gateway
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31000


